var dropdown_ = {
    "File" : {
        "New File" : "Ctrl+N",
        "Open File..." : "Ctrl+O",
        "Open Folder..." : "",
        "Open Recent" : [],
        "Reopen with Encoding" : [],
        "New View into File" : "",
        "Save" : "",
        "Save with Encoding" : "",
        "Save As..." : "Ctrl+Shift+S",
        "Save All" : "",
        "<span class='line'></span>" : "",
        "New Window" : "",
        "Close Window" : "",
        "<span class='line1'></span>" : "",
        "Close File" : "",
        "Revert File" : "",
        "Close All Files" : "",
        "<span class='line2'></span>" : "",
        "Exit" : ""

    },
    "Edit" : {
        "Undo Insert Characters" : "Ctrl+Z",
        "Repeat Insert Character" : "Ctrl+Y",
        "Undo Selection" : [],
        "<span class='line'></span>" : "",
        "Copy" : "",
        "Cut" : "",
        "Paste" : "",
        "Paste and Indent" : "",
        "Paste from History" : "",
        "<span class='line1'></span>" : "",
        "Line" : "",
        "Comment" : "",
        "Text" : "",
        "Tag" : "",
        "Code Folding" : "",
        "Convert Case" : "",
        "Wrap" : "",
        "Show Completions" : "Ctrl+Space",
        "<span class='line2'></span>" : "",

    },
    "Selection" : "",
    "Find" : "",
    "View" : "",
    "Goto" :"",
    "Tools" :"",
    "Project" :"",
    "Preferences" : "",
    "Help" : ""


}